[package]
name = "rpkg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
toml = "0.6"
serde = { version = "1.0", features = ["derive"] }
colored = "2.1.0"
zip = "0.6"

